# -*- coding: utf-8 -*-
"""DOc genie.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fOOJMY0o2cc0kRrvG0wMO6yBxdKM-Sro
"""

!pip install -U transformers

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe=pipeline("text-generation",model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role":"user","content":"Who are you?"},
]
pipe(messages)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer =AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role":"user","content":"Who are you?"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_tensors="pt",
).to(model.device)
outputs = model.generate(**inputs,max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True))

!pip install -q gradio transformers torch black autopep8 reportlab requests

import gradio

from datetime import datetime

from pathlib import Path

import json

import re

import ast

from reportlab.lib.pagesizes import letter, A4

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Preformatted
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from reportlab.lib.units import inch
from reportlab.lib import colors # Correcting based on common usage, assuming 'colors' is directly available under lib or will be accessed via colors module

import requests

import urllib.parse

import inspect

!pip install gradio transformers torch black autopep8 reportlab requests

import ast

class DocGenieAnalyzer:
    """Analyze Python functions and generate professional docstrings"""

    @staticmethod
    def extract_function_signature(code):
        """Extract function name, parameters, and return type from code."""
        try:
            tree = ast.parse(code)
            func_defs = [node for node in tree.body if isinstance(node, ast.FunctionDef)]

            if not func_defs:
                return None, None, None # No function definition found

            func_def = func_defs[0] # Take the first function definition if multiple exist
            func_name = func_def.name
            params = []

            # Handle parameters
            for i, arg in enumerate(func_def.args.args):
                param_info = {"name": arg.arg, "type": "Any", "default": None}
                if arg.annotation:
                    param_info["type"] = ast.unparse(arg.annotation) if hasattr(ast, 'unparse') else "Any"

                # Handle default values (only for args with defaults)
                num_defaults = len(func_def.args.defaults)
                if num_defaults > 0 and i >= len(func_def.args.args) - num_defaults:
                    default_value_node = func_def.args.defaults[i - (len(func_def.args.args) - num_defaults)]
                    param_info["default"] = ast.unparse(default_value_node) if hasattr(ast, 'unparse') else None
                params.append(param_info)

            # Handle return type
            return_type = "Any"
            if func_def.returns:
                return_type = ast.unparse(func_def.returns) if hasattr(ast, 'unparse') else "Any"

            return func_name, params, return_type

        except SyntaxError as e:
            print(f"SyntaxError in code: {e}")
            return None, None, None # Handle invalid code input
        except Exception as e:
            print(f"Error during signature extraction: {e}")
            return None, None, None

    @staticmethod
    def analyze_function_logic(func_def_node):
        """Deep analysis of a function's AST node to understand its behavior."""
        analysis = {
            'has_loops': False,
            'has_conditions': False,
            'has_return': False,
            'loop_types': set(), # Using set to avoid duplicates
            'condition_types': set(), # Using set to avoid duplicates
            'operations': set(),
            'return_values': set(),
            'variables_used': set(),
            'function_calls': set(),
            'description': ""
        }

        for node in ast.walk(func_def_node):
            if isinstance(node, (ast.For, ast.While)):
                analysis['has_loops'] = True
                analysis['loop_types'].add(type(node).__name__.lower())
            elif isinstance(node, (ast.If, ast.IfExp)):
                analysis['has_conditions'] = True
                analysis['condition_types'].add(type(node).__name__.lower())
            elif isinstance(node, ast.Return):
                analysis['has_return'] = True
                if node.value:
                    analysis['return_values'].add(ast.unparse(node.value) if hasattr(ast, 'unparse') else "unknown value")
            elif isinstance(node, ast.Name) and isinstance(node.ctx, (ast.Load, ast.Store)):
                analysis['variables_used'].add(node.id)
            elif isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name):
                    analysis['function_calls'].add(node.func.id)
                elif isinstance(node.func, ast.Attribute):
                    # For method calls like obj.method(), extract 'method'
                    analysis['function_calls'].add(node.func.attr)

        # Generate a descriptive summary
        description_parts = []
        if analysis['has_loops']:
            description_parts.append(f"It contains loops ({', '.join(sorted(analysis['loop_types']))}).")
        if analysis['has_conditions']:
            description_parts.append(f"It uses conditional statements ({', '.join(sorted(analysis['condition_types']))}).")
        if analysis['has_return']:
            returned_values = ', '.join(sorted(analysis['return_values']))
            description_parts.append(f"It returns a value{f', potentially: {returned_values}' if returned_values else ''}.")
        if analysis['variables_used']:
            description_parts.append(f"It uses variables such as: {', '.join(sorted(analysis['variables_used']))}.")
        if analysis['function_calls']:
            description_parts.append(f"It makes calls to functions like: {', '.join(sorted(analysis['function_calls']))}.")

        if not description_parts:
            description_parts.append("A simple function with no apparent loops, conditions, or function calls.")

        analysis['description'] = " ".join(description_parts)

        return analysis

# Example usage of the fixed DocGenieAnalyzer class
analyzer = DocGenieAnalyzer()

test_code = """
def calculate_sum(a: int, b: int = 10) -> int:
    result = a + b
    if result > 0:
        for i in range(result):
            print(i)
    return result
"""

# Extract signature
name, params, ret = analyzer.extract_function_signature(test_code)
print(f"Function: {name}")
print(f"Parameters: {params}")
print(f"Returns: {ret}")

# Analyze logic
tree = ast.parse(test_code)
func_node = [n for n in tree.body if isinstance(n, ast.FunctionDef)][0]
logic = analyzer.analyze_function_logic(func_node)
print(f"\nLogic Description: {logic['description']}")

# Example usage of the fixed DocGenieAnalyzer class
analyzer = DocGenieAnalyzer()

test_code = """
def calculate_sum(a: int, b: int = 10) -> int:
    result = a + b
    if result > 0:
        for i in range(result):
            print(i)
    return result
"""

# Extract signature
name, params, ret = analyzer.extract_function_signature(test_code)
print(f"Function: {name}")
print(f"Parameters: {params}")
print(f"Returns: {ret}")

# Analyze logic
tree = ast.parse(test_code)
func_node = [n for n in tree.body if isinstance(n, ast.FunctionDef)][0]
logic = analyzer.analyze_function_logic(func_node)
print(f"\nLogic Description: {logic['description']}")

# Example usage of the fixed DocGenieAnalyzer class to analyze logic
analyzer = DocGenieAnalyzer()

test_code = """
def process_data(data: list) -> bool:
    if not data:
        return False
    for item in data:
        print(f'Processing {item}')
    return True
"""

# Parse and analyze the logic
tree = ast.parse(test_code)
func_node = [n for n in tree.body if isinstance(n, ast.FunctionDef)][0]
logic = analyzer.analyze_function_logic(func_node)

print(f"Function Logic Analysis:\n{logic['description']}")

def generate_google_docstring(signature, analysis):
    """Generate accurate Google-style docstring"""
    summary = analysis.get('description', 'Processes input and returns result.')
    docstring = f'    """{summary}\n'

    if signature['params']:
        docstring += '\n    Args:\n'
        for param in signature['params']:
            default_str = f" (default: {param['default']})" if param['default'] else ""
            docstring += f"        {param['name']} ({param['type']}): Parameter for controlling {param['name']} behavior{default_str}.\n"

    docstring += f"\n    Returns:\n        {signature['return_type']}: The result of the computation.\n    """
    return docstring.strip()

# Example usage with previously extracted data
print("Generated Google-Style Docstring:")
try:
    # Using parameters from the previous successful analysis cells
    print(generate_google_docstring({'params': params, 'return_type': ret}, logic))
except NameError:
    print("Note: 'params' or 'logic' variables not found. Please run the analysis cells first.")

def generate_numpy_docstring(signature, analysis):
    """Generate accurate NumPy-style docstring"""
    summary = analysis.get('description', 'Processes input and returns result.')
    docstring = f'    """{summary}\n\n'

    if signature['params']:
        docstring += '    Parameters\n    ----------\n'
        for param in signature['params']:
            default_str = f", default: {param['default']}" if param['default'] else ""
            docstring += f"    {param['name']} : {param['type']}{default_str}\n"
            docstring += f"        Parameter for controlling {param['name']} behavior.\n"

    docstring += f"\n    Returns\n    -------\n    {signature['return_type']}\n"
    docstring += f"        The result of the computation.\n    """
    return docstring.strip()

analyzer = DocGenieAnalyzer()
generation_history = []

# Example usage
print("Generated NumPy-Style Docstring:")
try:
    # Using parameters from the previous successful analysis cells
    print(generate_numpy_docstring({'params': params, 'return_type': ret}, logic))
except NameError:
    print("Note: Analysis variables not found. Please run the previous analysis cells first.")

import gradio as gr
import ast

# Helper for file processing
def process_upload(file):
    if file is None: return "", "No file"
    try:
        with open(file.name, 'r') as f:
            return f.read(), "File uploaded successfully"
    except Exception as e:
        return "", f"Error: {str(e)}"

# Main generation logic
def generate_full_output(code, style):
    try:
        analyzer = DocGenieAnalyzer()
        name, params, ret = analyzer.extract_function_signature(code)
        if not name:
            return "# Error: No valid function definition found."

        tree = ast.parse(code)
        func_node = [n for n in tree.body if isinstance(n, ast.FunctionDef)][0]
        logic = analyzer.analyze_function_logic(func_node)

        if style == "google":
            docstring = generate_google_docstring({'params': params, 'return_type': ret}, logic)
        else:
            docstring = generate_numpy_docstring({'params': params, 'return_type': ret}, logic)

        # Insert docstring after function signature
        lines = code.split('\n')
        lines.insert(1, docstring)
        return '\n'.join(lines)
    except Exception as e:
        return f"# Error during generation: {str(e)}"

with gr.Blocks() as demo:
    gr.Markdown("## Professional Python Function Docstring Generator")

    with gr.Row():
        with gr.Column(scale=2):
            code_input = gr.Code(
                language="python",
                label="Input Python Code",
                lines=12,
                value="""def calculate_factorial(n):
    if n == 0:
        return 1
    return n * calculate_factorial(n-1)"""
            )
            file_upload = gr.File(label="Or Upload .py File", file_types=['.py'])

        with gr.Column(scale=1):
            docstring_style = gr.Radio(["google", "numpy"], value="google", label="Docstring Style")
            generate_btn = gr.Button("Generate Docstring", variant="primary")
            upload_status = gr.Textbox(label="Status", interactive=False)

    code_output = gr.Code(language="python", label="Result", lines=15)

    # Event Handlers
    file_upload.change(process_upload, inputs=[file_upload], outputs=[code_input, upload_status])
    generate_btn.click(generate_full_output, inputs=[code_input, docstring_style], outputs=[code_output])

demo.launch()

import gradio as gr
import ast

with gr.Blocks() as demo:
    gr.Markdown("### DocGenie Interface")

    # File Upload section
    file_upload = gr.File(label="Or Upload .py File", file_types=['.py'])
    upload_status = gr.Textbox(label="Upload Status", interactive=False, lines=1)

    # Style Selection section
    with gr.Row():
        docstring_style = gr.Radio(["google", "numpy"], value="google", label="Docstring Style")
        generate_btn = gr.Button("Generate Docstring", size="lg", variant="primary", scale=2)

    # Output Area
    gr.Markdown("### Generated Output")
    code_output = gr.Code(
        language="python",
        label="Function with Docstring",
        lines=15,
        interactive=False
    )

    # Event Handlers (assuming helpers are in global scope from previous cells)
    file_upload.change(process_upload, inputs=[file_upload], outputs=[upload_status])
    generate_btn.click(generate_full_output, inputs=[code_output, docstring_style], outputs=[code_output])

demo.launch()

import gradio as gr

def clear_history():
    return "History Cleared"

def generate_docstring(code, style):
    return f"# Result for {style} style\n" + code

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column(scale=2):
            code_input = gr.Code(language="python", label="Input Code")
            docstring_style = gr.Radio(["google", "numpy"], value="google", label="Docstring Style")
            generate_btn = gr.Button("Generate", variant="primary")

        with gr.Column(scale=1):
            gr.Markdown("### Controls")
            upload_status = gr.Textbox(label="Upload Status", interactive=False)
            gen_status = gr.Textbox(label="Status", interactive=False, lines=1)
            clear_btn = gr.Button("Clear History", variant="stop", size="sm")

            gr.Markdown("---")
            gr.Markdown("### Export")
            pdf_btn = gr.Button("Download PDF", size="sm", variant="primary")
            txt_btn = gr.Button("Download TXT", size="sm", variant="primary")
            pdf_file = gr.File(label="PDF File", visible=True)
            txt_file = gr.File(label="TXT File", visible=True)

    code_output = gr.Code(language="python", label="Result", interactive=False)

    # Event Handlers
    generate_btn.click(generate_docstring, inputs=[code_input, docstring_style], outputs=[code_output, gen_status])
    clear_btn.click(clear_history, outputs=[upload_status])

demo.launch()

import gradio as gr

# Placeholder functions for the sharing logic
def download_txt(): return "Status", None
def generate_whatsapp_link(): return "WhatsApp Link Generated"
def generate_facebook_link(): return "Facebook Link Generated"

with gr.Blocks() as demo:
    gr.Markdown("---")
    gr.Markdown("### Share")

    with gr.Row():
        whatsapp_btn = gr.Button("WhatsApp", size="sm", variant="secondary")
        facebook_btn = gr.Button("Facebook", size="sm", variant="secondary")

    share_output = gr.Textbox(label="Share Link", interactive=False, lines=4)

    whatsapp_btn.click(generate_whatsapp_link, outputs=[share_output])
    facebook_btn.click(generate_facebook_link, outputs=[share_output])

    gr.Markdown("---")
    gr.Markdown("""
    ### Features
    **Improvements:**
    * Accurate logic analysis
    * Contextual descriptions
    * Operation detection
    * Loop & condition recognition
    * Better PDF export
    * Consistent output
    """)

demo.launch()

def generate_whatsapp_link():
    """Generate WhatsApp share link"""
    if not generation_history:
        return "❌ No documentation to share!"

    message = "*Doc-Genie Documentation*\n\n"
    for i, gen in enumerate(generation_history[-3:], 1):
        message += f"*Doc {i}:*\n"
        message += f"Style: {gen['style']}\n"
        message += f" {gen['code'][:60]}...\n\n"

    encoded = urllib.parse.quote(message)
    link = f"https://wa.me/?text={encoded}"
    return f"WhatsApp Link:\n\n{link}\n\nShare with team!"

def generate_facebook_link():
    """Generate Facebook share link"""
    if not generation_history:
        return "❌ No documentation to share!"

    message = f"I generated {len(generation_history)} professional Python function docstrings with Doc-Genie! Check it out!"
    encoded = urllib.parse.quote(message)
    link = f"https://www.facebook.com/sharer/sharer.php?quote={encoded}"
    return f"Facebook Link:\n\n{link}"